services:
  freeso:
    build: .
    restart: unless-stopped
    ports:
      - 9000:9000/tcp
      - 33101:33101/tcp
      - 34101:34101/tcp
      - 35101:35101/tcp
    volumes:
      - ./config.json:/App/config.json:rw
      - ./Content:/App/Content:rw
      - ./version.txt:/App/version.txt:ro
      - ./simNFS:/simNFS:rw
      - ./game/TSOClient:/game:ro

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: fso
      MARIADB_USER: fsoserver
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306/tcp # Do not port forward this or at least change the default database credentials 
    volumes:
      - ./mariadb:/var/lib/mysql:rw
