name: Build server Docker image

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-amd64:
    name: Build for AMD64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./docker/Dockerfile
        pull: true
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}:git

  build-arm64:
    name: Build for ARM64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./docker/Dockerfile
        pull: true
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:git
