name: Build Server (Git)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/server-git.yml
      - .github/workflows/reusable-server-git.yml
      - TSOClient/FSO.Server
      - TSOClient/FSO.Common
      - TSOClient/FSO.Common.DatabaseService
      - TSOClient/FSO.Common.Domain
      - TSOClient/FSO.Content
      - TSOClient/FSO.Content.TSO
      - TSOClient/FSO.Files
      - TSOClient/FSO.LotView
      - TSOClient/FSO.Server.Api
      - TSOClient/FSO.Server.Client
      - TSOClient/FSO.Server.Datbase
      - TSOClient/FSO.Server.Domain
      - TSOClient/FSO.Server.Protocol
      - TSOClient/FSO.SimAntics
      - TSOClient/FSO.Vitaboy
      - Others/libs/TargaImgePCL
      - Other/libs/FSOMina.NET
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/server-git.yml
      - .github/workflows/reusable-server-git.yml
      - TSOClient/FSO.Server
      - TSOClient/FSO.Common
      - TSOClient/FSO.Common.DatabaseService
      - TSOClient/FSO.Common.Domain
      - TSOClient/FSO.Content
      - TSOClient/FSO.Content.TSO
      - TSOClient/FSO.Files
      - TSOClient/FSO.LotView
      - TSOClient/FSO.Server.Api
      - TSOClient/FSO.Server.Client
      - TSOClient/FSO.Server.Datbase
      - TSOClient/FSO.Server.Domain
      - TSOClient/FSO.Server.Protocol
      - TSOClient/FSO.SimAntics
      - TSOClient/FSO.Vitaboy
      - Others/libs/TargaImgePCL
      - Other/libs/FSOMina.NET

jobs:
  build-win-x64:
    name: Build for Windows x64
    uses: dark-steveneq/fsodotnet8.0/.github/workflows/reusable-server-git.yml@master
    with:
      platform: win-x64

  build-linux-x64:
    name: Build for Linux x64
    uses: dark-steveneq/fsodotnet8.0/.github/workflows/reusable-server-git.yml@master
    with:
      platform: linux-x64

  build-linux-arm64:
    name: Build for Linux Arm64
    uses: dark-steveneq/fsodotnet8.0/.github/workflows/reusable-server-git.yml@master
    with:
      platform: linux-arm64

  build-docker:
    name: Build Docker images
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./docker/Dockerfile
        pull: true
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:git
